blog/urls.py
from django.urls import path
from .import views

urlpatterns = [path( '', views.PostView.as_view() ),
               path( '<int:pk>/', views.PostDetail.as_view()),
               path( 'review/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
               path( '<int:pk>/add_likes/', views.AddLike.as_view(), name='add_Likes'),
               path( '<int:pk>/del_likes/', views.DelLike.as_view(), name='del_Likes')
               ]

catalog/urls.py
from django.urls import path
from .import views

urlpatterns = [path( '', views.Product.as_view() )
               ]

osergey_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('catalog', include('catalog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    # Данные поста
    title = models.CharField('Заголовок записи', max_length = 100)
    description = models.TextField('Текст записи') # полный текст
    summory = models.TextField('Описание') # описание
    category = models.CharField('Категория', max_length = 100) # категория
    author = models.CharField('Имя автора', max_length = 100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

class Comments(models.Model):
    """Коментарии"""
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)
    

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

class Likes(models.Model):
    """ Лайки """
    ip = models.CharField('IP-адрес', max_length = 50)
    pos = models.ForeignKey(Post, verbose_name = 'Публикация', on_delete=models.CASCADE)

catalog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post, Comments, Likes
from .form import CommentsForm

class PostView( View ):
    """выводы записей"""
    def get( self, request ):
        posts = Post.objects.all()
        comment_count = Comments.objects.count()
        return render(request, 'blog/blog.html', {'post_list': posts, 'comment_count': comment_count})

class PostDetail( View ):
    """ вывод записей """
    def get(self, request, pk):
        post = Post.objects.get( id = pk )
        return render( request, 'blog/blog_detail.html', { 'post': post } )
    
class AddComments(View):
    """Добавление коментариев"""
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect( f'/{pk}')
    
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

class AddLike(View):
    def get(self, request, pk):
        ip_clietn = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_clietn, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_Like = Likes()
            new_Like.ip = ip_clietn
            new_Like.pos_id = int(pk)
            new_Like.save()
            return redirect(f'/{pk}')  

class DelLike(View):
    def get(self, request, pk):
        ip_clietn = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_clietn)
            lik.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

catalog/views.py
from django.shortcuts import render
from django.views.generic.base import View

class Product( View ):
    pass
    def get( self, request ):
        return render(request, 'catalog/index.html')
        #return render(request, 'catalog/index.html', {'post_list': posts, 'comment_count': comment_count})

templates/blog/blog_detail.html
<!DOCTYPE html>
<html lang="ru-RU" prefix="og: https://ogp.me/ns#" itemtype="https://schema.org/Blog" itemscope>

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Блог. Главный сисадмин САО</title>
    <link rel="stylesheet" href={% static 'css/style.css' %} type="text/css" media="all" />

    <link rel="shortcut icon" href="css/images/favicon.ico" />
</head>

<body>
    <div class="shell">
        <div class="border">

            <div id="navigation">
                <ul>
                    <li><a href="/" class="active">Главная</a></li>
                    <li><a href="/admin">Админ панель</a></li>

                </ul>
            </div>

            <div id="main">
                <div id="content" class="left">

                    <div class="projects">
                        <h3> {{ post.title }} </h3>
                        
                        <p align="center">

                            <a href="#"><img class="post" src=" {{post.img.url}} " /></a>

                        </p>

                        <div class="item">

                            <div class="text left">
                                <h4> </h4>
                                <p> {{ post.description }} </p>
                                <p> {{ post.author }} </p>

                            </div>
                            <div class="cl">&nbsp;</div>
                        </div>

                    </div>
                </div>
                
                <div>
                    <br>
                    <p>Понравилось: {{ post.likes_set.all.count }} </p>
                    <br>
                    <a href="{% url 'add_Likes' post.id %}"> Нравится </a>
                    <a href="{% url 'del_Likes' post.id %}"> Не нравится </a>

                </div>

                <div class="form-coment">
                    <h3> Оставить комментарий </h3>
                    <div>
                        <form action=" {% url 'add_comments' post.id %} " method="post">
                            {% csrf_token %}
                            <div>
                                <label> Ваш комментарий </label>
                                <textarea name="text_comments"></textarea>
                            </div>
                            <div>
                                <label> Ваше имя * </label>
                                <input type="text" name="name">
                            </div>
                            <div>
                                <label> Ваш Email * </label>
                                <input type="email" name="email">
                            </div>
                            <div>
                                <input type="submit">
                            </div>
                        </form>
                    </div>
                </div>

                <div>
                    {% for comment in post.comments_set.all %}
                    <div class="view-comment">
                        <h4>{{ comment.name }}</h4>
                        <p>
                            {{ comment.text_comments }}
                        </p>
                    </div>
                    {% endfor %}
                </div>

                <div class="cl">&nbsp;</div>
            </div>


        </div>

        <div id="footer">
            <p class="copy right">Copyright &copy; 2022 </p>
        </div>
    </div>

</body>

</html>

templates/catalog/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Каталог!!!</title>
</head>

<body>
    <h1>Здесь каталог</h1>

    <div class="card" style="width: 18rem;">
        <img src="static/img_catalog/00-00004281.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">25361 Оправы корригирующих очков EYE VISION EY21184 C1 50-19-143</h5>
            <p class="card-text">текст</p>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">250 руб.</li>
            </ul>
            <a href="#" class="btn btn-primary">Подробнее</a>
        </div>

    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>